"""
app/domain/general/prompt_template.py
───────────────────────────────────────
Standard RAG prompt template for the general domain.

Goals:
  • Helpful and concise — answer the question directly from retrieved context.
  • Grounded — the model must rely on retrieved documents, not prior knowledge.
  • Honest — acknowledge when context is insufficient rather than fabricating.
  • Clean — no raw UUIDs or database IDs in the final output.
"""

from __future__ import annotations

import logging
from datetime import date

from app.core.config import Domain

logger = logging.getLogger(__name__)

# ── Disclaimer (lightweight — no regulatory requirements for general domain) ──
_DISCLAIMER = (
    "Note: This response is generated by an AI system based solely on the "
    "retrieved documents provided above. It may not reflect the most current "
    "information. Verify important facts with primary sources."
)

# ── System prompt ─────────────────────────────────────────────────────────────
_SYSTEM_PROMPT = """\
You are a precise, helpful research assistant. Your task is to answer the \
user's question using ONLY the information contained in the retrieved documents \
provided below.

## Rules

1. **Answer from context only**: Do not use prior knowledge. If the documents \
do not contain enough information, do not guess. Instead, explicitly state: \
"The retrieved context does not contain sufficient information to fully answer this."

2. **Ground in Specifics (CRITICAL)**: Anchor your answer in the specific examples, \
case studies, or historical facts mentioned in the text. Avoid vague, generic, or \
hypothetical answers. If the text mentions a specific system (like a sepsis tool or \
specific hospital deployment), you MUST use that exact example to support your reasoning.

3. **Synthesis and Categories**: When asked for a list, applications, or reasons, \
read ALL provided chunks. Identify high-level categories rather than just listing \
specific examples. Ensure you list ALL items found across the different chunks.

4. **Format**: Use clean Markdown bullet points for lists. Be concise and avoid \
unnecessary preamble.

5. **Clean Citations**: DO NOT output raw database UUIDs or formatting like \
`[Source: 69e7...]`. If you need to refer to a source, use natural language \
like "According to the document" or weave the fact naturally into your answer.

6. **Handle contradictions**: If retrieved documents disagree on a fact, report \
both perspectives.
"""

# ── Context block template ────────────────────────────────────────────────────
_CONTEXT_BLOCK = """\
### Document [{index}]
- **Source Name**: {source}
- **Section**: {section}

{text}
"""

_CITATION_INSTRUCTION = (
    "Remember: Do not use raw UUIDs. Synthesize the answer logically and use bullet points for lists."
)


class GeneralPromptTemplate:
    """
    Builds prompts for the general domain.
    """

    domain = Domain.GENERAL

    def system_prompt(self) -> str:
        return _SYSTEM_PROMPT

    def render(self, query: str, context_chunks: list[dict]) -> str:
        context_section = self._build_context_section(context_chunks)
        today           = date.today().isoformat()

        return f"""{_SYSTEM_PROMPT}

---

## Retrieved Documents ({len(context_chunks)} total) — {today}

{context_section}

---

## Question

{query.strip()}

{_CITATION_INSTRUCTION}
"""

    def _build_context_section(self, chunks: list[dict]) -> str:
        if not chunks:
            return "_No relevant documents were retrieved for this query._"

        blocks: list[str] = []
        for i, chunk in enumerate(chunks, start=1):
            meta    = chunk.get("metadata", {})
            source  = meta.get("source", meta.get("filename", "unknown"))
            section = chunk.get("section") or meta.get("section", "N/A")
            text    = chunk.get("text", "").strip()

            blocks.append(
                _CONTEXT_BLOCK.format(
                    index=i,
                    source=source,
                    section=section,
                    text=text,
                )
            )

        return "\n".join(blocks)

    @staticmethod
    def ensure_disclaimer(text: str) -> str:
        if _DISCLAIMER[:30] not in text:
            return text.rstrip() + f"\n\n---\n{_DISCLAIMER}"
        return text

    @staticmethod
    def disclaimer() -> str:
        return _DISCLAIMER