"""
app/retrieval/sparse_retriever.py
──────────────────────────────────
Sparse retrieval using SPLADE sparse vectors stored natively in Qdrant.

Why Qdrant-native sparse vectors instead of rank-bm25 / in-memory BM25:
  • rank-bm25 builds its entire index in RAM — at scale (millions of chunks)
    this exhausts available memory and violates the "no in-memory indexing"
    requirement.
  • Qdrant's sparse vector support (introduced in v1.7) stores the inverted
    index on disk alongside the dense HNSW index, using the same payload
    filtering and ACL logic with zero additional infrastructure.
  • SPLADE (Sparse Lexical and Expansion model) produces learned sparse
    vectors that outperform BM25 on BEIR benchmarks while maintaining full
    lexical interpretability.

Sparse vector format in Qdrant:
  Each sparse vector is a ``SparseVector(indices=[...], values=[...])``
  where ``indices`` are vocabulary token IDs and ``values`` are the
  corresponding SPLADE weights.  Qdrant performs a dot-product over only
  the non-zero dimensions, making it equivalent to an inverted-index lookup.

Ingestion requirement (enforced in ingest.py, not here):
  Documents must have been indexed with BOTH a dense vector (``vector``)
  AND a sparse vector (``sparse_vector`` named field).  The sparse vector
  is generated by the same SPLADE model used here for query encoding.

SPLADE model: ``prithivida/Splade_PP_en_v1``
  • 30 522-dim sparse output (BERT vocabulary size)
  • Encodes query → dict{token_id: weight} via MLM head + ReLU + log(1+x)
  • Lightweight: 110 M params, ~400 ms cold inference on CPU
  • Loaded once, lazy, behind an asyncio.Lock (same pattern as domain embedders)
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Any

from qdrant_client import AsyncQdrantClient
from qdrant_client.models import (
    NamedSparseVector,
    SparseVector,
)

from app.core.config import Domain, get_settings
from app.core.models import DocumentChunk, RetrievalFilter, RetrievalResult
from app.core.observability import get_tracer, span
from app.core.qdrant_client import get_qdrant_client
from app.retrieval.dense_retriever import _assign_ranks, _build_filter

logger = logging.getLogger(__name__)
tracer = get_tracer()

# Name of the sparse vector field registered on every Qdrant collection.
# Must match the field name used during ingestion upserts.
SPARSE_VECTOR_FIELD = "sparse"


# ══════════════════════════════════════════════════════════════════════════════
# SPLADE encoder  (lazy singleton, async-safe)
# ══════════════════════════════════════════════════════════════════════════════

class _SpladeEncoder:
    """
    Wraps ``prithivida/Splade_PP_en_v1`` to encode text → sparse vector.

    Lazy-loaded on first use.  The asyncio.Lock prevents concurrent
    initialisation races at cold-start without blocking the event loop —
    the blocking ``transformers`` load is dispatched to the thread pool.
    """

    MODEL_NAME = "prithivida/Splade_PP_en_v1"

    def __init__(self) -> None:
        self._tokenizer: Any   = None
        self._model:     Any   = None
        self._device:    str   = "cpu"
        self._lock       = asyncio.Lock()
        self._ready      = False

    async def ensure_loaded(self) -> None:
        """Load model if not yet loaded.  Safe to call concurrently."""
        if self._ready:
            return
        async with self._lock:
            if self._ready:   # double-checked locking
                return
            with span("sparse_retriever.load_splade"):
                logger.info(
                    "Loading SPLADE encoder",
                    extra={"model": self.MODEL_NAME},
                )
                loop = asyncio.get_event_loop()
                await loop.run_in_executor(None, self._load_blocking)
                self._ready = True
                logger.info("SPLADE encoder ready")

    def _load_blocking(self) -> None:
        """Blocking model/tokenizer load — runs in thread-pool executor."""
        from transformers import AutoModelForMaskedLM, AutoTokenizer
        import torch

        self._device    = "cuda" if torch.cuda.is_available() else "cpu"
        self._tokenizer = AutoTokenizer.from_pretrained(self.MODEL_NAME)
        self._model     = AutoModelForMaskedLM.from_pretrained(self.MODEL_NAME)
        self._model.eval()
        self._model.to(self._device)

        # Warm-up pass to trigger JIT / kernel compilation
        self._encode_blocking(["warm-up query"])
        logger.debug("SPLADE warm-up complete", extra={"device": self._device})

    async def encode(self, text: str) -> SparseVector:
        """
        Encode a single query string into a Qdrant ``SparseVector``.

        Returns a ``SparseVector(indices, values)`` with only non-zero
        dimensions included — typically 50–200 non-zero weights per query.
        """
        await self.ensure_loaded()
        with span("sparse_retriever.encode_query"):
            loop = asyncio.get_event_loop()
            return await loop.run_in_executor(None, self._encode_single, text)

    def _encode_single(self, text: str) -> SparseVector:
        """Synchronous SPLADE encoding.  Runs in thread-pool executor."""
        return self._encode_blocking([text])[0]

    def _encode_blocking(self, texts: list[str]) -> list[SparseVector]:
        """
        Encode a list of texts to SPLADE sparse vectors.

        Algorithm:
          1. Tokenise with truncation at 512 tokens.
          2. Forward pass through the MLM head.
          3. Apply ReLU + log(1 + x) activation (SPLADE transformation).
          4. Max-pool over the sequence dimension → one weight per vocab token.
          5. Extract non-zero (index, value) pairs.
        """
        import torch

        assert self._tokenizer is not None and self._model is not None

        inputs = self._tokenizer(
            texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=512,
        )
        inputs = {k: v.to(self._device) for k, v in inputs.items()}

        with torch.no_grad():
            logits = self._model(**inputs).logits             # (B, T, V)

        # SPLADE activation: ReLU(log(1 + max_pool(logits, dim=T)))
        # max over token dimension → (B, V)
        token_weights = torch.log1p(torch.relu(logits))
        sparse_reps   = token_weights.max(dim=1).values       # (B, V)

        results: list[SparseVector] = []
        for rep in sparse_reps:
            non_zero  = rep.nonzero(as_tuple=False).squeeze(1)
            indices   = non_zero.tolist()
            values    = rep[non_zero].tolist()
            results.append(SparseVector(indices=indices, values=values))

        return results


# Module-level singleton — created once, shared across all requests
_splade_encoder = _SpladeEncoder()


def get_splade_encoder() -> _SpladeEncoder:
    """Return the shared SPLADE encoder instance."""
    return _splade_encoder


# ══════════════════════════════════════════════════════════════════════════════
# Sparse Retriever
# ══════════════════════════════════════════════════════════════════════════════

class SparseRetriever:
    """
    Performs sparse vector search against the per-domain Qdrant collection.

    Usage::

        retriever = SparseRetriever()
        result = await retriever.retrieve(
            domain=Domain.MEDICAL,
            query="metformin dosage type 2 diabetes",
            top_k=20,
            filter=RetrievalFilter(domain="medical", acl="public"),
        )
    """

    def __init__(
        self,
        client:  AsyncQdrantClient | None = None,
        encoder: _SpladeEncoder | None    = None,
    ) -> None:
        self._settings = get_settings()
        self._client   = client   # injected or resolved lazily
        self._encoder  = encoder or _splade_encoder

    # ── Public API ─────────────────────────────────────────────────────────────

    async def retrieve(
        self,
        domain:  Domain,
        query:   str,
        top_k:   int | None = None,
        filter:  RetrievalFilter | None = None,
    ) -> RetrievalResult:
        """
        Encode ``query`` with SPLADE and run a sparse vector search in Qdrant.

        Args:
            domain:  Target domain — determines which collection to query.
            query:   Raw query string (not pre-embedded).
            top_k:   Number of results to return.  Defaults to
                     ``settings.retrieval_top_k_sparse``.
            filter:  Optional payload filter (domain, doc_id, ACL).

        Returns:
            ``RetrievalResult`` with ``stage="sparse"`` and ranked chunks.
        """
        top_k      = top_k or self._settings.retrieval_top_k_sparse
        collection = self._settings.qdrant_collection_name(domain)
        client     = self._client or get_qdrant_client()

        # Encode query → sparse vector (async-safe, lazy loads model)
        sparse_vector = await self._encoder.encode(query)

        qdrant_filter = (
            _build_filter(filter) if filter and not filter.is_empty() else None
        )

        with span(
            "retrieval.sparse_search",
            domain=domain.value,
            collection=collection,
            top_k=top_k,
            nnz=len(sparse_vector.indices),
        ):
            t0 = time.perf_counter()
            try:
                hits = await client.search(
                    collection_name=collection,
                    query_vector=NamedSparseVector(
                        name=SPARSE_VECTOR_FIELD,
                        vector=sparse_vector,
                    ),
                    query_filter=qdrant_filter,
                    limit=top_k,
                    with_payload=True,
                    with_vectors=False,
                )
            except Exception as exc:
                logger.error(
                    "Sparse retrieval failed",
                    extra={"domain": domain.value, "error": str(exc)},
                )
                raise

            latency_ms = (time.perf_counter() - t0) * 1000

        chunks = [DocumentChunk.from_qdrant_hit(h) for h in hits]
        _assign_ranks(chunks)

        logger.debug(
            "Sparse retrieval complete",
            extra={
                "domain":     domain.value,
                "n_hits":     len(chunks),
                "latency_ms": round(latency_ms, 2),
                "nnz":        len(sparse_vector.indices),
            },
        )

        return RetrievalResult(
            chunks=chunks,
            stage="sparse",
            total=len(chunks),
            latency_ms=latency_ms,
        )


# ── FastAPI dependency ────────────────────────────────────────────────────────

_sparse_retriever_singleton: SparseRetriever | None = None


def get_sparse_retriever() -> SparseRetriever:
    """Return the application-scoped SparseRetriever singleton."""
    global _sparse_retriever_singleton
    if _sparse_retriever_singleton is None:
        _sparse_retriever_singleton = SparseRetriever()
    return _sparse_retriever_singleton
