"""
app/domain/financial/prompt_template.py
────────────────────────────────────────
Domain-specific prompt templates for the financial domain.

Template hierarchy:
  1. SYSTEM_PROMPT  — static, injected once per session / streaming request.
  2. render()       — combines system prompt + dynamic RAG context + query.
  3. CITATION_INSTRUCTION — appended to every user turn.
"""

from __future__ import annotations

import logging
from datetime import date

from app.core.config import Domain

logger = logging.getLogger(__name__)

# ── SEC / compliance disclaimer ───────────────────────────────────────────────
_DISCLAIMER = (
    "IMPORTANT DISCLOSURE: This response is generated by an AI system for "
    "informational purposes only. It does not constitute investment advice, "
    "a solicitation, or a recommendation to buy or sell any security. "
    "Past performance is not indicative of future results. "
    "Always consult a qualified financial advisor before making investment decisions. "
    "Information may not reflect the most recent filings or market conditions."
)

# ── System prompt ─────────────────────────────────────────────────────────────
_SYSTEM_PROMPT = """You are a highly accurate, professional financial research assistant with deep expertise \
in SEC filings, financial statements, and regulatory disclosures.

## Core Behavioural Rules

1. **Strict Grounding (No External Knowledge)**: You must base your answer SOLELY on the provided retrieved context. \
If the answer is not fully supported by the context, respond EXACTLY with: \
"The provided documents do not contain sufficient information to answer this question." \
NEVER use external, prior, or general knowledge to fill in gaps. 

2. **Clean, Concise & Cohesive Output**: Synthesize the information into clear, professional paragraphs. \
Keep your answers focused and avoid unnecessary verbosity. NEVER output raw citation tags like `[Source: ...]`, \
UUIDs, or internal document IDs. Integrate source names naturally into your sentences ONLY if necessary for clarity.

3. **No Repetition**: NEVER repeat the same sentence, paragraph, or concept twice in your response. Make your \
point once, clearly, and move on.

4. **Source Fidelity**: Reproduce financial figures (revenue, EPS, ratios) VERBATIM from the provided context. \
Do NOT round, estimate, or interpolate numbers.

5. **Confident Tone & Explanation Depth**: When explaining financial concepts, ensure you explain the "why" \
based on the context. Answer directly and confidently. DO NOT use weak, defensive meta-commentary \
(e.g., "The context does not provide further explanation" or "Based on the retrieved documents..."). State the facts.

6. **Summarization Style**: When asked to summarize, write cohesive, professional paragraphs summarizing \
the RETRIEVED CONTEXT. Do NOT output fragmented bulleted lists unless explicitly requested.

7. **Temporal Precision**: Explicitly state the fiscal period (e.g., "FY2023 Q3") for every data point if provided.

8. **Regulatory Language**: When discussing forward-looking statements, prepend \
"This contains forward-looking statements subject to material risks and uncertainties".

9. **Table Interpretation**: When reading tables, read row-by-row and column-by-column carefully.

10. **Comparison Discipline**: When comparing periods, present all figures in the same unit and explicitly state the unit.

11. **No Disclaimers**: You are an internal analysis tool. DO NOT output ANY legal, financial, or advisory \
disclaimers (e.g., "This is not financial advice...").
"""

# ── Context block template ────────────────────────────────────────────────────
_CONTEXT_BLOCK_TEMPLATE = """\
### Retrieved Document [{index}]
- **Source**: {source}
- **Section**: {section}
- **Date**: {date}
- **Chunk type**: {chunk_type}
- **Relevance score**: {score:.4f}

{text}
"""

# ── Citation instruction (appended to every user turn) ───────────────────────
_CITATION_INSTRUCTION = (
    "Base your entire answer strictly on the provided context. "
    "Do NOT use bracketed citation tags (e.g., [Source: ...]). "
    "Synthesize the information into a cohesive, professional, concise, and readable response. "
    "If the context does not contain the answer, state that explicitly without guessing."
)


class FinancialPromptTemplate:
    """
    Builds prompts for the financial domain.
    """

    domain = Domain.FINANCIAL

    # ── Protocol: system_prompt ───────────────────────────────────────────────

    def system_prompt(self) -> str:
        """Return the static financial system prompt."""
        return _SYSTEM_PROMPT

    # ── Protocol: render ──────────────────────────────────────────────────────

    def render(self, query: str, context_chunks: list[dict]) -> str:
        """Render the full prompt to be sent to the LLM."""
        context_section = self._build_context_section(context_chunks)
        today = date.today().isoformat()

        return f"""{_SYSTEM_PROMPT}

---

## Retrieved Context
The following {len(context_chunks)} document excerpt(s) have been retrieved as \
relevant to the query. Today's date is {today}.

{context_section}

---

## User Query

{query.strip()}

{_CITATION_INSTRUCTION}
"""

    # ── Context section builder ───────────────────────────────────────────────

    def _build_context_section(self, chunks: list[dict]) -> str:
        """Format retrieved chunks into a numbered, labelled context block."""
        if not chunks:
            return "_No relevant documents were retrieved for this query._"

        blocks: list[str] = []
        for i, chunk in enumerate(chunks, start=1):
            meta       = chunk.get("metadata", {})
            source     = meta.get("source", meta.get("filename", "unknown"))
            section    = chunk.get("section") or meta.get("section", "N/A")
            doc_date   = meta.get("filing_date") or meta.get("date", "N/A")
            chunk_type = chunk.get("chunk_type", "narrative")
            score      = chunk.get("score", 0.0)
            text       = chunk.get("text", "").strip()

            # Prepend table reading hint
            if chunk_type == "table":
                row_range = chunk.get("row_range", "")
                range_note = f" (rows {row_range})" if row_range else ""
                text = (
                    f"[TABLE{range_note} — read each cell value carefully]\n\n"
                    + text
                )

            block = _CONTEXT_BLOCK_TEMPLATE.format(
                index=i,
                source=source,
                section=section,
                date=doc_date,
                chunk_type=chunk_type,
                score=score,
                text=text,
            )
            blocks.append(block)

        return "\n".join(blocks)

    # ── Compliance guardrail helpers ──────────────────────────────────────────

    @staticmethod
    def inject_forward_looking_warning(text: str) -> str:
        """Prepend the SEC safe-harbour caveat if forward-looking language is detected."""
        forward_looking_triggers = (
            "will ", "expect", "anticipat", "project", "forecast",
            "guidance", "outlook", "plan to", "intend", "believe",
        )
        lower = text.lower()
        if any(t in lower for t in forward_looking_triggers):
            warning = (
                "⚠️ **Forward-Looking Statement Notice**: The following response "
                "may contain forward-looking statements. Such statements involve "
                "known and unknown risks, uncertainties, and other factors that "
                "could cause actual results to differ materially from those expressed "
                "or implied. See the company's SEC filings for a complete discussion "
                "of risk factors.\n\n"
            )
            return warning + text
        return text

    @staticmethod
    def ensure_disclaimer(text: str) -> str:
        """Disabled the forced disclaimer injection."""
        return text

    @staticmethod
    def disclaimer() -> str:
        """Return the raw disclaimer string for use in streaming post-processing."""
        return _DISCLAIMER